import React, { useEffect, useState } from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.jsx'
import './index.css'
import { client } from '../tina/__generated__/client' // This is generated by Tina

const TinaWrapper = () => {
  const [tinaData, setTinaData] = useState(null);

  useEffect(() => {
    // Fetch the data from your markdown files via the Tina client
    const fetchData = async () => {
      const res = await client.queries.page({ relativePath: 'home.md' });
      setTinaData(res);
    };
    fetchData();
  }, []);

  if (!tinaData) return <div className="bg-black h-screen" />; // Loading state

  return (
    <App 
      data={tinaData.data} 
      query={tinaData.query} 
      variables={tinaData.variables} 
    />
  );
};

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <TinaWrapper />
  </React.StrictMode>,
)